### ISSUE TITLE
Menu item "challenge" disappeared on staging

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1218]
**Describe the bug**
The menu item "challenge" is not displayed any more.

**Is it on a Production or Development Build?**
development (staging)

**To Reproduce**
Steps to reproduce the behavior: Just open the website https://staging.trilliontreecampaign.org/

**Expected behavior**
Show the menu item as on production.

**What actually happens**
The menu item is missing.

**Screenshots**
Staging:
<img width="259" alt="Bildschirmfoto 2019-08-11 um 14 58 56" src="https://user-images.githubusercontent.com/1532418/62835582-87a00300-bc5a-11e9-8505-14b4fc3a371a.png">

Production:
<img width="260" alt="Bildschirmfoto 2019-08-11 um 14 58 49" src="https://user-images.githubusercontent.com/1532418/62835586-8d95e400-bc5a-11e9-91de-e4bac260eba8.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
 - Browser: latest Chrome
 - Plant-for-the-Planet App Version 1.0.3

**Comment by jmiridis** [comment]
Menu item for challenge is being loaded as inActive by default
```
    web_main_3_1:
        menuGroup: "@web_main_3"
        slug: challenge
        minVersion: 101000
        caption: menu_item.challenge
        help: menu_item.challenge.help
        icon: "challenge_outline"
        uri: "app_challenge"
        roles: [ROLE_PUBLIC, ROLE_TREEDONOR, ROLE_TPO]
        sequence: 1
        isActive: 0
```
Everytime the database is being rebuilt, it will be created like this.
I can change this now and add a commit on `develop` to solve for the future.
